# Generated by Django 4.2 on 2023-04-14 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnomalyClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter anomaly class short name",
                        max_length=32,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Toolset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter toolset short name", max_length=32, unique=True
                    ),
                ),
                (
                    "detector",
                    models.BinaryField(help_text="Serialized data for detector"),
                ),
                (
                    "classifier",
                    models.BinaryField(
                        help_text="Serialized data for classifier", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnomalyClassMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index",
                    models.PositiveSmallIntegerField(
                        help_text="Index of anomaly class detected by classifier"
                    ),
                ),
                (
                    "anomaly_class",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mtehis_web.anomalyclass",
                    ),
                ),
                (
                    "toolset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mtehis_web.toolset"
                    ),
                ),
            ],
            options={
                "ordering": ["index", "toolset"],
            },
        ),
        migrations.CreateModel(
            name="Anomaly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inputs", models.BinaryField()),
                ("detector_scores", models.BinaryField()),
                ("classifier_scores", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "label",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mtehis_web.anomalyclass",
                    ),
                ),
                (
                    "toolset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mtehis_web.toolset"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
