# Generated by Django 4.2 on 2023-04-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mtehis_web", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="anomalyclassmapping",
            unique_together={("toolset", "anomaly_class"), ("toolset", "index")},
        ),
    ]
